//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 1993 - 2000 California Institute of Technology             //
//                                                                          //
// Read the COPYING and README files, or contact 'avida@alife.org',         //
// before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     //
//////////////////////////////////////////////////////////////////////////////
#ifndef EVENT_DEFS_HH
#define EVENT_DEFS_HH
enum eEvent { EVENT_undefined = 0,
EVENT_exit,
EVENT_pause,
EVENT_echo,
EVENT_print_event_list,
EVENT_print_average_data,
EVENT_print_error_data,
EVENT_print_variance_data,
EVENT_print_dominant_data,
EVENT_print_stats_data,
EVENT_print_count_data,
EVENT_print_totals_data,
EVENT_print_tasks_data,
EVENT_print_time_data,
EVENT_print_mutation_data,
EVENT_perturb_tasks,
EVENT_change_tasks,
EVENT_print_task_bonus,
EVENT_print_instruction_data,
EVENT_print_dom_instruction_data,
EVENT_print_depth_histogram,
EVENT_print_dom,
EVENT_save_clone,
EVENT_load_clone,
EVENT_inject,
EVENT_inject_all,
EVENT_inject_random,
EVENT_mod_copy_mut,
EVENT_set_copy_mut,
EVENT_mod_point_mut,
EVENT_set_point_mut,
EVENT_calc_landscape,
EVENT_predict_w_landscape,
EVENT_predict_nu_landscape,
EVENT_random_landscape,
EVENT_analyze_landscape,
EVENT_pairtest_landscape,
EVENT_pairtest_full_landscape,
EVENT_analyze_tasksites,
EVENT_test_dom,
EVENT_hillclimb,
EVENT_hillclimb_neut,
EVENT_hillclimb_rand,
EVENT_calc_consensus,
EVENT_test_size_change_robustness,
EVENT_test_threads,
EVENT_print_threads,
EVENT_dump_basic_grid,
EVENT_dump_fitness_grid,
EVENT_NO_EVENT };
#endif
