//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 1993 - 2000 California Institute of Technology             //
//                                                                          //
// Read the COPYING and README files, or contact 'avida@alife.org',         //
// before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     //
//////////////////////////////////////////////////////////////////////////////
// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef cDialogWindow_hh
#define cDialogWindow_hh
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>

class cDialogWindow {
  bool close_dialog;
public:
  cDialogWindow(const char * label, const char * mesg);
private:
  Fl_Window *dialog_window;
  Fl_Output *dialog_text;
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  ~cDialogWindow();
  void Block();
};
#endif
