//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 1993 - 2000 California Institute of Technology             //
//                                                                          //
// Read the COPYING and README files, or contact 'avida@alife.org',         //
// before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     //
//////////////////////////////////////////////////////////////////////////////
// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef cMapTestUI_hh
#define cMapTestUI_hh
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Output.H>
#include <Fl/Fl_Scroll.h>
#include "legend.hh"
#include <FL/Fl_Box.H>
#include "grid.hh"

class cMapTestUI {
public:
  cMapTestUI(int x_size, int y_size);
  Fl_Double_Window *map_window;
  Fl_Value_Slider *zoom_slider;
private:
  inline void cb_zoom_slider_i(Fl_Value_Slider*, void*);
  static void cb_zoom_slider(Fl_Value_Slider*, void*);
public:
  Fl_Group *pan_group;
private:
  inline void cb_Y_i(Fl_Roller*, void*);
  static void cb_Y(Fl_Roller*, void*);
  inline void cb_X_i(Fl_Roller*, void*);
  static void cb_X(Fl_Roller*, void*);
public:
  Fl_Output *origin_label;
  cLegend *legend;
  cGrid *grid;
  void show();
  ~cMapTestUI();
};
#endif
