//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 1993 - 2000 California Institute of Technology             //
//                                                                          //
// Read the COPYING and README files, or contact 'avida@alife.org',         //
// before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     //
//////////////////////////////////////////////////////////////////////////////
// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "cMapTestUI.hh"
#include <iostream.h>
#include <Fl/fl_ask.h>

inline void cMapTestUI::cb_zoom_slider_i(Fl_Value_Slider* o, void*) {
  legend->SetCellSize(((Fl_Slider*)o)->value() );
}
void cMapTestUI::cb_zoom_slider(Fl_Value_Slider* o, void* v) {
  ((cMapTestUI*)(o->parent()->user_data()))->cb_zoom_slider_i(o,v);
}

inline void cMapTestUI::cb_Y_i(Fl_Roller* o, void*) {
  if(  ((Fl_Roller*)o)->value() >= 1 )
 ((Fl_Roller*)o)->value( ((Fl_Roller*)o)->value()-1 );
if(  ((Fl_Roller*)o)->value() < 0 )
 ((Fl_Roller*)o)->value( ((Fl_Roller*)o)->value()+1 );
grid->SetYOrigin( ((Fl_Roller*)o)->value() * grid->GetRows() );
origin_label->value(grid->GetOriginString());
}
void cMapTestUI::cb_Y(Fl_Roller* o, void* v) {
  ((cMapTestUI*)(o->parent()->parent()->user_data()))->cb_Y_i(o,v);
}

inline void cMapTestUI::cb_X_i(Fl_Roller* o, void*) {
  if(  ((Fl_Roller*)o)->value() >= 1 )
 ((Fl_Roller*)o)->value( ((Fl_Roller*)o)->value()-1 );
if(  ((Fl_Roller*)o)->value() < 0 )
 ((Fl_Roller*)o)->value( ((Fl_Roller*)o)->value()+1 );
grid->SetXOrigin( ((Fl_Roller*)o)->value() *grid->GetCols() );
origin_label->value(grid->GetOriginString());
}
void cMapTestUI::cb_X(Fl_Roller* o, void* v) {
  ((cMapTestUI*)(o->parent()->parent()->user_data()))->cb_X_i(o,v);
}

cMapTestUI::cMapTestUI(int x_size, int y_size) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = map_window = new Fl_Double_Window(701, 498, "Map");
    w = o;
    o->user_data((void*)(this));
    { Fl_Value_Slider* o = zoom_slider = new Fl_Value_Slider(150, 470, 230, 20, "Zoom");
      o->type(1);
      o->minimum(1);
      o->maximum(20);
      o->step(1);
      o->value(5);
      o->callback((Fl_Callback*)cb_zoom_slider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Group* o = pan_group = new Fl_Group(0, 5, 665, 440);
      o->align(FL_ALIGN_BOTTOM_LEFT|FL_ALIGN_INSIDE);
      { Fl_Roller* o = new Fl_Roller(10, 220, 20, 170, "Y");
        o->minimum(-0.9);
        o->maximum(1.9);
        o->step(0.005);
        o->callback((Fl_Callback*)cb_Y);
      }
      { Fl_Roller* o = new Fl_Roller(65, 415, 180, 20, "X");
        o->type(1);
        o->minimum(-0.9);
        o->maximum(1.9);
        o->step(0.005);
        o->callback((Fl_Callback*)cb_X);
        o->align(FL_ALIGN_LEFT);
      }
      { Fl_Output* o = origin_label = new Fl_Output(560, 15, 105, 20, "Origin:");
        o->box(FL_FLAT_BOX);
        o->color(49);
      }
      o->end();
    }
    { Fl_Scroll* o = new Fl_Scroll(465, 130, 200, 280, "Legend");
      o->box(FL_ENGRAVED_BOX);
      { cLegend* o = legend = new cLegend(470, 135, 160, 270);
        o->labeltype(FL_NO_LABEL);
        o->align(FL_ALIGN_TOP);
      }
      o->end();
    }
    { Fl_Box* o = new Fl_Box(40, 5, 415, 405);
      o->box(FL_ENGRAVED_FRAME);
    }
    grid = new cGrid(40, 5, 415, 405);
    o->end();
  }
  grid->SetupSize(x_size, y_size, legend);
}

void cMapTestUI::show() {
  map_window->show();
  grid->show();
  legend->show();
}

cMapTestUI::~cMapTestUI() {
  map_window->hide();
  Fl::wait(0.025);
}
