//////////////////////////////////////////////////////////////////////////////
// Copyright (C) 1993 - 2000 California Institute of Technology             //
//                                                                          //
// Read the COPYING and README files, or contact 'avida@alife.org',         //
// before continuing.  SOME RESTRICTIONS MAY APPLY TO USE OF THIS FILE.     //
//////////////////////////////////////////////////////////////////////////////
// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef cMapWindowUI_hh
#define cMapWindowUI_hh
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Light_Button.H>
#include <Fl/Fl_Scroll.h>
#include "legend.hh"
#include <FL/Fl_Box.H>
#include "grid.hh"

class cMapWindowUI {
public:
  int mode;
  cMapWindowUI(int x_size, int y_size);
  Fl_Double_Window *map_window;
private:
  inline void cb_map_window_i(Fl_Double_Window*, void*);
  static void cb_map_window(Fl_Double_Window*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Value_Slider *zoom_slider;
private:
  inline void cb_zoom_slider_i(Fl_Value_Slider*, void*);
  static void cb_zoom_slider(Fl_Value_Slider*, void*);
public:
  Fl_Group *pan_group;
private:
  inline void cb_Y_i(Fl_Roller*, void*);
  static void cb_Y(Fl_Roller*, void*);
  inline void cb_X_i(Fl_Roller*, void*);
  static void cb_X(Fl_Roller*, void*);
public:
  Fl_Output *center_label;
private:
  inline void cb_Threshold_i(Fl_Light_Button*, void*);
  static void cb_Threshold(Fl_Light_Button*, void*);
  inline void cb_Birth_i(Fl_Light_Button*, void*);
  static void cb_Birth(Fl_Light_Button*, void*);
  inline void cb_Genotype_i(Fl_Light_Button*, void*);
  static void cb_Genotype(Fl_Light_Button*, void*);
public:
  cLegend *legend;
  Fl_Light_Button *pause_button;
private:
  inline void cb_pause_button_i(Fl_Light_Button*, void*);
  static void cb_pause_button(Fl_Light_Button*, void*);
public:
  cGrid *grid;
  void show();
  ~cMapWindowUI();
};
#endif
